stages:
  - build
  - test
  - deploy

variables:
  RULES_CHANGES_PATH: "**/*"

.base-rules:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - $RULES_CHANGES_PATH
    - when: manual
      allow_failure: true

.backend:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "backend/**/*"

.frontend:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "frontend/**/*"

backend-build:
  stage: build
  extends: .backend
  image: node:latest
  needs: []
  tags:
    - shared-fi
  script:
    - cd backend
    - npm i
    - npm run build
    

backend-eslint:
  stage: build
  extends: .backend
  image: node:latest
  tags: 
    - shared-fi
  script:
    - cd backend
    - npm install
    - npx eslint .

frontend-build:
  stage: build
  extends: .frontend
  image: node:latest
  needs: []
  tags:
    - shared-fi
  script:
    - cd frontend
    - npm i
    - npm run build

frrontend-eslint:
  stage: build
  extends: .frontend
  image: node:latest
  tags: 
    - shared-fi
  script:
    - cd frontend
    - npm install
    - npx eslint .

backend-test:
  stage: test
  extends: .backend
  needs: ["backend-build"]
  tags:
    - shared-fi
  script:
    - echo "Testing the backend code..."

frontend-test:
  stage: test
  extends: .frontend
  needs: ["frontend-build"]
  tags:
    - shared-fi
  script:
    - echo "Testing the frontend code..."

