INSERT INTO public."Genre" (id, name) VALUES
                              (gen_random_uuid(), 'All'),
                              (gen_random_uuid(), 'Blues'),
                              (gen_random_uuid(), 'Classic rock'),
                              (gen_random_uuid(), 'Country'),
                              (gen_random_uuid(), 'Dance'),
                              (gen_random_uuid(), 'Disco'),
                              (gen_random_uuid(), 'Funk'),
                              (gen_random_uuid(), 'Grunge'),
                              (gen_random_uuid(), 'Hip-hop'),
                              (gen_random_uuid(), 'Jazz'),
                              (gen_random_uuid(), 'Metal'),
                              (gen_random_uuid(), 'New age'),
                              (gen_random_uuid(), 'Oldies'),
                              (gen_random_uuid(), 'Other'),
                              (gen_random_uuid(), 'Pop'),
                              (gen_random_uuid(), 'Rhythm and blues'),
                              (gen_random_uuid(), 'Rap'),
                              (gen_random_uuid(), 'Reggae'),
                              (gen_random_uuid(), 'Rock'),
                              (gen_random_uuid(), 'Techno'),
                              (gen_random_uuid(), 'Industrial'),
                              (gen_random_uuid(), 'Alternative'),
                              (gen_random_uuid(), 'Ska'),
                              (gen_random_uuid(), 'Death metal'),
                              (gen_random_uuid(), 'Pranks'),
                              (gen_random_uuid(), 'Soundtrack'),
                              (gen_random_uuid(), 'Euro-techno'),
                              (gen_random_uuid(), 'Ambient'),
                              (gen_random_uuid(), 'Trip-hop'),
                              (gen_random_uuid(), 'Vocal'),
                              (gen_random_uuid(), 'Jazz & funk'),
                              (gen_random_uuid(), 'Fusion'),
                              (gen_random_uuid(), 'Trance'),
                              (gen_random_uuid(), 'Classical'),
                              (gen_random_uuid(), 'Instrumental'),
                              (gen_random_uuid(), 'Acid'),
                              (gen_random_uuid(), 'House'),
                              (gen_random_uuid(), 'Game'),
                              (gen_random_uuid(), 'Sound clip'),
                              (gen_random_uuid(), 'Gospel'),
                              (gen_random_uuid(), 'Noise'),
                              (gen_random_uuid(), 'Alternative rock'),
                              (gen_random_uuid(), 'Bass'),
                              (gen_random_uuid(), 'Soul'),
                              (gen_random_uuid(), 'Punk'),
                              (gen_random_uuid(), 'Space'),
                              (gen_random_uuid(), 'Meditative'),
                              (gen_random_uuid(), 'Instrumental pop'),
                              (gen_random_uuid(), 'Instrumental rock'),
                              (gen_random_uuid(), 'Ethnic'),
                              (gen_random_uuid(), 'Gothic'),
                              (gen_random_uuid(), 'Darkwave'),
                              (gen_random_uuid(), 'Techno-industrial'),
                              (gen_random_uuid(), 'Electronic'),
                              (gen_random_uuid(), 'Pop-folk'),
                              (gen_random_uuid(), 'Eurodance'),
                              (gen_random_uuid(), 'Dream'),
                              (gen_random_uuid(), 'Southern rock'),
                              (gen_random_uuid(), 'Comedy'),
                              (gen_random_uuid(), 'Cult'),
                              (gen_random_uuid(), 'Gangsta'),
                              (gen_random_uuid(), 'Top 40'),
                              (gen_random_uuid(), 'Christian rap'),
                              (gen_random_uuid(), 'Pop/funk'),
                              (gen_random_uuid(), 'Jungle music'),
                              (gen_random_uuid(), 'Native US'),
                              (gen_random_uuid(), 'Cabaret'),
                              (gen_random_uuid(), 'New wave'),
                              (gen_random_uuid(), 'Psychedelic'),
                              (gen_random_uuid(), 'Rave'),
                              (gen_random_uuid(), 'Showtunes'),
                              (gen_random_uuid(), 'Trailer'),
                              (gen_random_uuid(), 'Lo-fi'),
                              (gen_random_uuid(), 'Tribal'),
                              (gen_random_uuid(), 'Acid punk'),
                              (gen_random_uuid(), 'Acid jazz'),
                              (gen_random_uuid(), 'Polka'),
                              (gen_random_uuid(), 'Retro'),
                              (gen_random_uuid(), 'Musical'),
                              (gen_random_uuid(), 'Rock n roll'),
                              (gen_random_uuid(), 'Hard rock'),
                              (gen_random_uuid(), 'Folk'),
                              (gen_random_uuid(), 'Folk rock'),
                              (gen_random_uuid(), 'National folk'),
                              (gen_random_uuid(), 'Swing'),
                              (gen_random_uuid(), 'Fast fusion'),
                              (gen_random_uuid(), 'Bebop'),
                              (gen_random_uuid(), 'Latin'),
                              (gen_random_uuid(), 'Revival'),
                              (gen_random_uuid(), 'Celtic'),
                              (gen_random_uuid(), 'Bluegrass'),
                              (gen_random_uuid(), 'Avantgarde'),
                              (gen_random_uuid(), 'Gothic rock'),
                              (gen_random_uuid(), 'Progressive rock'),
                              (gen_random_uuid(), 'Psychedelic rock'),
                              (gen_random_uuid(), 'Symphonic rock'),
                              (gen_random_uuid(), 'Slow rock'),
                              (gen_random_uuid(), 'Big band'),
                              (gen_random_uuid(), 'Chorus'),
                              (gen_random_uuid(), 'Easy listening'),
                              (gen_random_uuid(), 'Acoustic'),
                              (gen_random_uuid(), 'Humour'),
                              (gen_random_uuid(), 'Speech'),
                              (gen_random_uuid(), 'Chanson'),
                              (gen_random_uuid(), 'Opera'),
                              (gen_random_uuid(), 'Chamber music'),
                              (gen_random_uuid(), 'Sonata'),
                              (gen_random_uuid(), 'Symphony'),
                              (gen_random_uuid(), 'Booty bass'),
                              (gen_random_uuid(), 'Primus'),
                              (gen_random_uuid(), 'Porn groove'),
                              (gen_random_uuid(), 'Satire'),
                              (gen_random_uuid(), 'Slow jam'),
                              (gen_random_uuid(), 'Club'),
                              (gen_random_uuid(), 'Tango'),
                              (gen_random_uuid(), 'Samba'),
                              (gen_random_uuid(), 'Folklore'),
                              (gen_random_uuid(), 'Ballad'),
                              (gen_random_uuid(), 'Power ballad'),
                              (gen_random_uuid(), 'Rhythmic soul'),
                              (gen_random_uuid(), 'Freestyle'),
                              (gen_random_uuid(), 'Duet'),
                              (gen_random_uuid(), 'Punk rock'),
                              (gen_random_uuid(), 'Drum solo'),
                              (gen_random_uuid(), 'A cappella'),
                              (gen_random_uuid(), 'Euro-house'),
                              (gen_random_uuid(), 'Dance hall'),
                              (gen_random_uuid(), 'Goa'),
                              (gen_random_uuid(), 'Drum & bass'),
                              (gen_random_uuid(), 'Club-house'),
                              (gen_random_uuid(), 'Hardcore techno'),
                              (gen_random_uuid(), 'Terror'),
                              (gen_random_uuid(), 'Indie'),
                              (gen_random_uuid(), 'Britpop'),
                              (gen_random_uuid(), 'Negerpunk'),
                              (gen_random_uuid(), 'Polsk punk'),
                              (gen_random_uuid(), 'Beat'),
                              (gen_random_uuid(), 'Christian gangsta rap'),
                              (gen_random_uuid(), 'Heavy metal'),
                              (gen_random_uuid(), 'Black metal'),
                              (gen_random_uuid(), 'Crossover'),
                              (gen_random_uuid(), 'Contemporary Christian'),
                              (gen_random_uuid(), 'Christian rock'),
                              (gen_random_uuid(), 'Merengue'),
                              (gen_random_uuid(), 'Salsa'),
                              (gen_random_uuid(), 'Thrash metal'),
                              (gen_random_uuid(), 'Anime'),
                              (gen_random_uuid(), 'Jpop'),
                              (gen_random_uuid(), 'Synthpop'),
                              (gen_random_uuid(), 'Christmas'),
                              (gen_random_uuid(), 'Art rock'),
                              (gen_random_uuid(), 'Baroque'),
                              (gen_random_uuid(), 'Bhangra'),
                              (gen_random_uuid(), 'Big beat'),
                              (gen_random_uuid(), 'Breakbeat'),
                              (gen_random_uuid(), 'Chillout'),
                              (gen_random_uuid(), 'Downtempo'),
                              (gen_random_uuid(), 'Dub'),
                              (gen_random_uuid(), 'EBM'),
                              (gen_random_uuid(), 'Eclectic'),
                              (gen_random_uuid(), 'Electro'),
                              (gen_random_uuid(), 'Electroclash'),
                              (gen_random_uuid(), 'Emo'),
                              (gen_random_uuid(), 'Experimental'),
                              (gen_random_uuid(), 'Garage'),
                              (gen_random_uuid(), 'Global'),
                              (gen_random_uuid(), 'IDM'),
                              (gen_random_uuid(), 'Illbient'),
                              (gen_random_uuid(), 'Industro-Goth'),
                              (gen_random_uuid(), 'Jam band'),
                              (gen_random_uuid(), 'Krautrock'),
                              (gen_random_uuid(), 'Leftfield'),
                              (gen_random_uuid(), 'Lounge'),
                              (gen_random_uuid(), 'Math rock'),
                              (gen_random_uuid(), 'New romantic'),
                              (gen_random_uuid(), 'Nu-breakz'),
                              (gen_random_uuid(), 'Post-punk'),
                              (gen_random_uuid(), 'Post-rock'),
                              (gen_random_uuid(), 'Psytrance'),
                              (gen_random_uuid(), 'Shoegaze'),
                              (gen_random_uuid(), 'Space rock'),
                              (gen_random_uuid(), 'Trop rock'),
                              (gen_random_uuid(), 'World music'),
                              (gen_random_uuid(), 'Neoclassical'),
                              (gen_random_uuid(), 'Audiobook'),
                              (gen_random_uuid(), 'Audio theatre'),
                              (gen_random_uuid(), 'Neue Deutsche Welle'),
                              (gen_random_uuid(), 'Podcast'),
                              (gen_random_uuid(), 'Indie-rock'),
                              (gen_random_uuid(), 'G-Funk'),
                              (gen_random_uuid(), 'Dubstep'),
                              (gen_random_uuid(), 'Garage rock'),
                              (gen_random_uuid(), 'Psybient');

INSERT INTO public."Store" ("id", "name", "imageUrl", "url")
VALUES ('3ca22494-047e-11ee-be56-0242ac120002', 'Vinyl Pursuit', 'https://cdn.shopify.com/s/files/1/0535/5493/8031/files/Vinyl_Pursuit-Logo-Shopify_2048x_c69c5b46-53bd-48fa-88a4-c80cd7acc141_2048x.png?v=1673748459', 'vinylpursuit.com');

INSERT INTO public."Store" ("id", "name", "imageUrl", "url")
VALUES ('44758828-047e-11ee-be56-0242ac120002', 'Experience Vinyl', 'https://cdn.shopify.com/s/files/1/2236/3463/files/logo-reverse2.png?v=1614303994&width=250', 'experiencevinyl.com');

INSERT INTO public."Store" ("id", "name", "imageUrl", "url")
VALUES ('4a0b0b4a-047e-11ee-be56-0242ac120002', 'Music Stack', 'https://www.musicstack.com/gif/musicstack-logo.gif', 'musicstack.com');
