INSERT INTO public."Genre" (name) VALUES
                              ('All'),
                              ('Blues'),
                              ('Classic rock'),
                              ('Country'),
                              ('Dance'),
                              ('Disco'),
                              ('Funk'),
                              ('Grunge'),
                              ('Hip-hop'),
                              ('Jazz'),
                              ('Metal'),
                              ('New age'),
                              ('Oldies'),
                              ('Other'),
                              ('Pop'),
                              ('Rhythm and blues'),
                              ('Rap'),
                              ('Reggae'),
                              ('Rock'),
                              ('Techno'),
                              ('Industrial'),
                              ('Alternative'),
                              ('Ska'),
                              ('Death metal'),
                              ('Pranks'),
                              ('Soundtrack'),
                              ('Euro-techno'),
                              ('Ambient'),
                              ('Trip-hop'),
                              ('Vocal'),
                              ('Jazz & funk'),
                              ('Fusion'),
                              ('Trance'),
                              ('Classical'),
                              ('Instrumental'),
                              ('Acid'),
                              ('House'),
                              ('Game'),
                              ('Sound clip'),
                              ('Gospel'),
                              ('Noise'),
                              ('Alternative rock'),
                              ('Bass'),
                              ('Soul'),
                              ('Punk'),
                              ('Space'),
                              ('Meditative'),
                              ('Instrumental pop'),
                              ('Instrumental rock'),
                              ('Ethnic'),
                              ('Gothic'),
                              ('Darkwave'),
                              ('Techno-industrial'),
                              ('Electronic'),
                              ('Pop-folk'),
                              ('Eurodance'),
                              ('Dream'),
                              ('Southern rock'),
                              ('Comedy'),
                              ('Cult'),
                              ('Gangsta'),
                              ('Top 40'),
                              ('Christian rap'),
                              ('Pop/funk'),
                              ('Jungle music'),
                              ('Native US'),
                              ('Cabaret'),
                              ('New wave'),
                              ('Psychedelic'),
                              ('Rave'),
                              ('Showtunes'),
                              ('Trailer'),
                              ('Lo-fi'),
                              ('Tribal'),
                              ('Acid punk'),
                              ('Acid jazz'),
                              ('Polka'),
                              ('Retro'),
                              ('Musical'),
                              ('Rock n roll'),
                              ('Hard rock'),
                              ('Folk'),
                              ('Folk rock'),
                              ('National folk'),
                              ('Swing'),
                              ('Fast fusion'),
                              ('Bebop'),
                              ('Latin'),
                              ('Revival'),
                              ('Celtic'),
                              ('Bluegrass'),
                              ('Avantgarde'),
                              ('Gothic rock'),
                              ('Progressive rock'),
                              ('Psychedelic rock'),
                              ('Symphonic rock'),
                              ('Slow rock'),
                              ('Big band'),
                              ('Chorus'),
                              ('Easy listening'),
                              ('Acoustic'),
                              ('Humour'),
                              ('Speech'),
                              ('Chanson'),
                              ('Opera'),
                              ('Chamber music'),
                              ('Sonata'),
                              ('Symphony'),
                              ('Booty bass'),
                              ('Primus'),
                              ('Porn groove'),
                              ('Satire'),
                              ('Slow jam'),
                              ('Club'),
                              ('Tango'),
                              ('Samba'),
                              ('Folklore'),
                              ('Ballad'),
                              ('Power ballad'),
                              ('Rhythmic soul'),
                              ('Freestyle'),
                              ('Duet'),
                              ('Punk rock'),
                              ('Drum solo'),
                              ('A cappella'),
                              ('Euro-house'),
                              ('Dance hall'),
                              ('Goa'),
                              ('Drum & bass'),
                              ('Club-house'),
                              ('Hardcore techno'),
                              ('Terror'),
                              ('Indie'),
                              ('Britpop'),
                              ('Negerpunk'),
                              ('Polsk punk'),
                              ('Beat'),
                              ('Christian gangsta rap'),
                              ('Heavy metal'),
                              ('Black metal'),
                              ('Crossover'),
                              ('Contemporary Christian'),
                              ('Christian rock'),
                              ('Merengue'),
                              ('Salsa'),
                              ('Thrash metal'),
                              ('Anime'),
                              ('Jpop'),
                              ('Synthpop'),
                              ('Christmas'),
                              ('Art rock'),
                              ('Baroque'),
                              ('Bhangra'),
                              ('Big beat'),
                              ('Breakbeat'),
                              ('Chillout'),
                              ('Downtempo'),
                              ('Dub'),
                              ('EBM'),
                              ('Eclectic'),
                              ('Electro'),
                              ('Electroclash'),
                              ('Emo'),
                              ('Experimental'),
                              ('Garage'),
                              ('Global'),
                              ('IDM'),
                              ('Illbient'),
                              ('Industro-Goth'),
                              ('Jam band'),
                              ('Krautrock'),
                              ('Leftfield'),
                              ('Lounge'),
                              ('Math rock'),
                              ('New romantic'),
                              ('Nu-breakz'),
                              ('Post-punk'),
                              ('Post-rock'),
                              ('Psytrance'),
                              ('Shoegaze'),
                              ('Space rock'),
                              ('Trop rock'),
                              ('World music'),
                              ('Neoclassical'),
                              ('Audiobook'),
                              ('Audio theatre'),
                              ('Neue Deutsche Welle'),
                              ('Podcast'),
                              ('Indie-rock'),
                              ('G-Funk'),
                              ('Dubstep'),
                              ('Garage rock'),
                              ('Psybient');

INSERT INTO public."Store"
VALUES (1, 'Vinyl Pursuit', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'https://cdn.shopify.com/s/files/1/0535/5493/8031/files/Vinyl_Pursuit-Logo-Shopify_2048x_c69c5b46-53bd-48fa-88a4-c80cd7acc141_2048x.png?v=1673748459', 'vinylpursuit.com');

INSERT INTO public."Store"
VALUES (2, 'test', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'test', 'test');
